__author__ = 'Gareth Coles'

YAML = "Yaml"
JSON = "JSON"
SQLITE = "SQLite"
MEMORY = "Memory"
DBAPI = "DBAPI"

DATA = [YAML, JSON, SQLITE, MEMORY, DBAPI]
CONF = [YAML, JSON, MEMORY]
ALL = [YAML, JSON, SQLITE, MEMORY]
